export default function MessageBubble({ message }) {
  const isUser = message.role === 'user';

  return (
    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div
        className={`max-w-2xl px-4 py-3 rounded-lg ${
          isUser
            ? 'bg-jet-black border-2 border-arceus-orange text-white-accent'
            : 'bg-charcoal bg-opacity-60 text-white-accent'
        }`}
      >
        <div className="text-sm whitespace-pre-wrap break-words">{message.content}</div>
        {!isUser && message.model_used && (
          <div className="mt-2 pt-2 border-t border-gray-700 text-xs text-gray-500">
            Generated by {message.model_used}
          </div>
        )}
      </div>
    </div>
  );
}
